title: yusufcaliskan
description: personal website
url: https://yusufcaliskan.github.io
baseurl: https://yusufcaliskan.github.io
theme: minima
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-feed
gems:
  - jekyll-paginate
header:
  - Home: /
  - About: /about/
footer:
  - Contact: /contact /
